name: Ruby CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - name: Compile Assets
        run: |
          bin/rails assets:precompile
      - name: Run tests
        run: |
          bin/rails test
      - name: Report coverage
        if: github.event_name == 'pull_request'
        uses: aki77/simplecov-report-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install dependencies
        task:
          jobs:
            - name: pnpm install
              commands:
                - curl -f https://get.pnpm.io/v6.16.js | node - add --global pnpm@7
                - checkout
                - cache restore node-$(checksum pnpm-lock.yaml)
                - pnpm install
                - cache store node-$(checksum pnpm-lock.yaml) $(pnpm store path)
